"""
reports/report_generator.py
============================
Generates a self-contained HTML report from the change log file.
No external dependencies — pure Python + inline CSS/JS.
"""

import os
from datetime import datetime
from utils.helpers import parse_log_file, severity_color, now_iso


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Registry Monitor Report — {generated_at}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Segoe UI',system-ui,sans-serif;background:#0f0f10;color:#c2c0b6;line-height:1.6;padding:2rem}}
  h1{{font-size:1.5rem;font-weight:700;color:#fff;margin-bottom:.25rem}}
  .sub{{font-size:.85rem;color:#73726c;margin-bottom:2rem;font-family:'Consolas',monospace}}
  .stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:2rem}}
  .stat{{background:#1a1a1c;border:0.5px solid #2e2e30;border-radius:8px;padding:1rem}}
  .stat-label{{font-size:.75rem;color:#73726c;margin-bottom:.3rem}}
  .stat-val{{font-size:1.8rem;font-weight:700}}
  .stat-val.red{{color:#E24B4A}}.stat-val.amber{{color:#EF9F27}}.stat-val.blue{{color:#378ADD}}.stat-val.green{{color:#639922}}
  table{{width:100%;border-collapse:collapse;font-size:.85rem;background:#1a1a1c;border-radius:8px;overflow:hidden}}
  th{{background:#252527;color:#fff;font-weight:600;text-align:left;padding:.6rem .9rem;border-bottom:0.5px solid #2e2e30}}
  td{{padding:.55rem .9rem;border-bottom:0.5px solid #222224;vertical-align:top;word-break:break-word}}
  tr:last-child td{{border-bottom:none}}
  tr:hover td{{background:#202022}}
  .badge{{display:inline-block;padding:2px 8px;border-radius:4px;font-size:.75rem;font-family:'Consolas',monospace;font-weight:600}}
  .high{{background:#3a1515;color:#E24B4A}}.medium{{background:#3a2a10;color:#EF9F27}}.low{{background:#0e2035;color:#378ADD}}
  .alert-badge{{background:#3a1515;color:#E24B4A}}.warn-badge{{background:#3a2a10;color:#EF9F27}}.info-badge{{background:#0e2035;color:#378ADD}}
  .ts{{font-family:'Consolas',monospace;color:#73726c;white-space:nowrap}}
  .msg{{color:#c2c0b6}}
  .footer{{margin-top:2rem;font-size:.8rem;color:#444441;font-family:'Consolas',monospace}}
  h2{{font-size:1rem;font-weight:600;color:#fff;margin:2rem 0 .75rem}}
  .filter-row{{display:flex;gap:8px;margin-bottom:1rem;flex-wrap:wrap}}
  .filter-btn{{background:#1a1a1c;border:0.5px solid #2e2e30;color:#c2c0b6;
               padding:4px 14px;border-radius:4px;cursor:pointer;font-size:.8rem}}
  .filter-btn.active{{background:#252527;border-color:#5F5E5A;color:#fff}}
</style>
</head>
<body>
<h1>&#x1F6E1;&#xFE0F; Windows Registry Monitor — Change Report</h1>
<p class="sub">Generated: {generated_at} &nbsp;|&nbsp; Log file: {log_file}</p>

<div class="stats">
  <div class="stat"><div class="stat-label">Total log entries</div><div class="stat-val blue">{total}</div></div>
  <div class="stat"><div class="stat-label">ALERT (ERROR)</div><div class="stat-val red">{alerts}</div></div>
  <div class="stat"><div class="stat-label">WARN</div><div class="stat-val amber">{warns}</div></div>
  <div class="stat"><div class="stat-label">INFO / OK</div><div class="stat-val green">{infos}</div></div>
</div>

<h2>Log entries</h2>
<div class="filter-row">
  <button class="filter-btn active" onclick="filterTable('ALL')">All</button>
  <button class="filter-btn" onclick="filterTable('ERROR')">&#x26A0; Alerts</button>
  <button class="filter-btn" onclick="filterTable('WARNING')">&#x2757; Warnings</button>
  <button class="filter-btn" onclick="filterTable('INFO')">&#x2139; Info</button>
</div>
<table id="log-table">
  <thead><tr><th>Timestamp</th><th>Level</th><th>Message</th></tr></thead>
  <tbody>
{rows}
  </tbody>
</table>

<p class="footer">
  Registry Monitoring System &mdash; Blue Team Toolkit &nbsp;|&nbsp;
  Report generated by reports/report_generator.py
</p>

<script>
function filterTable(level) {{
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
  const rows = document.querySelectorAll('#log-table tbody tr');
  rows.forEach(r => {{
    r.style.display = (level === 'ALL' || r.dataset.level === level) ? '' : 'none';
  }});
}}
</script>
</body>
</html>
"""

_LEVEL_BADGE = {
    "ERROR":    '<span class="badge alert-badge">ALERT</span>',
    "WARNING":  '<span class="badge warn-badge">WARN</span>',
    "INFO":     '<span class="badge info-badge">INFO</span>',
    "DEBUG":    '<span class="badge info-badge">DEBUG</span>',
    "CRITICAL": '<span class="badge alert-badge">CRITICAL</span>',
}


class ReportGenerator:
    def __init__(self, log_file: str, output_path: str, logger):
        self.log_file    = log_file
        self.output_path = output_path
        self.logger      = logger

    def generate(self):
        entries = parse_log_file(self.log_file)

        alerts = sum(1 for e in entries if e["level"] in ("ERROR", "CRITICAL"))
        warns  = sum(1 for e in entries if e["level"] == "WARNING")
        infos  = sum(1 for e in entries if e["level"] in ("INFO", "DEBUG"))

        rows_html = []
        for e in entries:
            badge = _LEVEL_BADGE.get(e["level"], e["level"])
            msg   = e["message"].replace("<", "&lt;").replace(">", "&gt;")
            rows_html.append(
                f'    <tr data-level="{e["level"]}">'
                f'<td class="ts">{e["timestamp"]}</td>'
                f'<td>{badge}</td>'
                f'<td class="msg">{msg}</td>'
                f'</tr>'
            )

        html = _HTML_TEMPLATE.format(
            generated_at = now_iso(),
            log_file     = self.log_file,
            total        = len(entries),
            alerts       = alerts,
            warns        = warns,
            infos        = infos,
            rows         = "\n".join(rows_html) if rows_html else
                           '    <tr><td colspan="3" style="text-align:center;color:#444">No entries found.</td></tr>',
        )

        os.makedirs(os.path.dirname(self.output_path) or ".", exist_ok=True)
        with open(self.output_path, "w", encoding="utf-8") as fh:
            fh.write(html)

        self.logger.info(
            f"Report written to '{self.output_path}' "
            f"({len(entries)} entries: {alerts} alerts, {warns} warnings)"
        )
